# Copyright (C) 2019 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license
# (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).
max_iter: 100000              # maximum number of training iterations 110000
# data options
eval_shot: 1
eval_query: 15
pool_size: 100                 # candidate neighbour size
way_size: 5
num_workers: 4
new_size: 84        
batch_size: 1         
crop_image_height: 84        # random crop image of this height
crop_image_width: 84        # random crop image of this width
data_folder_train: /mnt/hdd/yw/miniimagenet/images
data_list_train: /mnt/hdd/yw/miniimagenet/train.txt
data_folder_test: /mnt/hdd/yw/miniimagenet/images
data_list_test: /mnt/hdd/yw/miniimagenet/test.txt
dataset: 'miniImagenet'